# Generated by Django 5.2.4 on 2025-08-27 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshop', '0002_package_description_alter_workshop_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haberdashery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('workers', models.ManyToManyField(blank=True, related_name='haberdashery', to='workshop.worker')),
                ('workshop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='haberdashery', to='workshop.workshop')),
            ],
            options={
                'verbose_name': 'Haberdashery',
                'verbose_name_plural': 'Haberdasheries',
            },
        ),
        migrations.CreateModel(
            name='TypeArticleInHaberdashery',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('is_delete', models.BooleanField(default=False)),
                ('haberdashery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_article', to='haberdashery.haberdashery')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleInHaberdashery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=0)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_out', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('type_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_article', to='haberdashery.typearticleinhaberdashery')),
            ],
            options={
                'verbose_name': 'Article dans le Haberdashery',
                'verbose_name_plural': 'Articles dans le Haberdashery',
                'ordering': ['-createdAt'],
            },
        ),
    ]
