# Generated by Django 5.2.4 on 2025-09-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleInHaberdashery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.SmallIntegerField(default=0)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_out', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article dans le Haberdashery',
                'verbose_name_plural': 'Articles dans le Haberdashery',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Haberdashery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Haberdashery',
                'verbose_name_plural': 'Haberdasheries',
            },
        ),
        migrations.CreateModel(
            name='TypeArticleInHaberdashery',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': "Type d'article dans le Haberdashery",
                'verbose_name_plural': "Types d'articles dans le Haberdashery",
                'ordering': ['name'],
            },
        ),
    ]
