# Generated by Django 5.2.4 on 2025-09-03 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('haberdashery', '0001_initial'),
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haberdashery',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='haberdashery', to='workshop.worker'),
        ),
        migrations.AddField(
            model_name='haberdashery',
            name='workshop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='haberdashery', to='workshop.workshop'),
        ),
        migrations.AddField(
            model_name='typearticleinhaberdashery',
            name='haberdashery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_articles', to='haberdashery.haberdashery'),
        ),
        migrations.AddField(
            model_name='articleinhaberdashery',
            name='type_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='haberdashery.typearticleinhaberdashery'),
        ),
        migrations.AlterUniqueTogether(
            name='typearticleinhaberdashery',
            unique_together={('name', 'haberdashery')},
        ),
        migrations.AlterUniqueTogether(
            name='articleinhaberdashery',
            unique_together={('name', 'type_article')},
        ),
    ]
