# Generated by Django 5.2.4 on 2025-08-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberdashery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typearticleinhaberdashery',
            options={'ordering': ['name'], 'verbose_name': "Type d'article dans le Haberdashery", 'verbose_name_plural': "Types d'articles dans le Haberdashery"},
        ),
        migrations.AddField(
            model_name='articleinhaberdashery',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
