# Generated by Django 5.2.4 on 2025-08-27 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberdashery', '0002_alter_typearticleinhaberdashery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinhaberdashery',
            name='type_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='haberdashery.typearticleinhaberdashery'),
        ),
        migrations.AlterField(
            model_name='typearticleinhaberdashery',
            name='haberdashery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_articles', to='haberdashery.haberdashery'),
        ),
        migrations.AlterField(
            model_name='typearticleinhaberdashery',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='articleinhaberdashery',
            unique_together={('name', 'type_article')},
        ),
        migrations.AlterUniqueTogether(
            name='typearticleinhaberdashery',
            unique_together={('name', 'haberdashery')},
        ),
    ]
