# Generated by Django 5.2.4 on 2025-08-27 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshop', '0002_package_description_alter_workshop_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=50)),
                ('scheduled_for', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_notifications', to='workshop.customerworkshop')),
            ],
        ),
        migrations.CreateModel(
            name='InternalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('success', 'Succès')], default='info', max_length=50)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('WORKER_CREATION', 'Worker Creation'), ('WORKER_UPDATE', 'Worker Update'), ('CUSTOMER_CREATION', 'Customer Creation'), ('CUSTOMER_UPDATE', 'Customer Update'), ('CUSTOMER_DELETION', 'Customer Deletion'), ('ORDER_CREATION', 'Order Creation'), ('ORDER_UPDATE', 'Order Update'), ('ORDER_DELETION', 'Order Deletion'), ('ORDER_GROUP_CREATION', 'Order Group Creation'), ('ORDER_GROUP_UPDATE', 'Order Group Update'), ('ORDER_GROUP_DELETION', 'Order Group Deletion'), ('FITTING_CREATION', 'Fitting Creation'), ('FITTING_UPDATE', 'Fitting Update'), ('FITTING_DELETION', 'Fitting Deletion'), ('WORKSHOP_CREATION', 'Workshop Creation'), ('WORKSHOP_UPDATE', 'Workshop Update'), ('AUTHORISATION_ACCEPT', 'Authorisation Accept'), ('AUTHORISATION_REJECT', 'Authorisation Reject'), ('SETTING_CREATION', 'Setting Creation'), ('SETTING_UPDATE', 'Setting Update')], max_length=50, null=True)),
                ('object_content', models.CharField(choices=[('Setting', 'Setting'), ('Worker', 'Worker'), ('Customer', 'Customer'), ('Order', 'Order'), ('OrderGroup', 'OrderGroup'), ('Fitting', 'Fitting'), ('Workshop', 'Workshop')], max_length=50)),
                ('object_pk', models.CharField(blank=True, max_length=225, null=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Internal Notification',
                'verbose_name_plural': 'Internal Notifications',
                'ordering': ['-createdAt'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_abd520_idx')],
            },
        ),
    ]
