# Generated by Django 5.2.4 on 2025-08-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalnotification',
            name='object_content',
            field=models.CharField(blank=True, choices=[('Setting', 'Setting'), ('Worker', 'Worker'), ('Customer', 'Customer'), ('Order', 'Order'), ('OrderGroup', 'OrderGroup'), ('Fitting', 'Fitting'), ('Workshop', 'Workshop')], max_length=50, null=True),
        ),
    ]
